//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotnetWebApp_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        public int EmployeeID { get; set; }
        public string Ename { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
    }
}
